### ISSUE TITLE
[RFE] Add support for vTPM

### ISSUE THREAD

**Issue by myllynen** [hashicorp/packer-plugin-qemu#83]
#### Description

Windows 11 requires a TPM device to install. It would be helpful to have `vTPM` configuration option supported by the QEMU builder is already supported by vSphere builder.

#### Use Case(s)

Allows installing Windows 11 using Packer/QEMU.

#### Potential configuration

```
vTPM: true
```

#### Potential References

https://www.packer.io/plugins/builders/vsphere/vsphere-iso

**Comment by lbajolet-hashicorp** [comment]
Hi @myllynen,

I've opened a PR with basic vTPM support, v1.2 and v2.0, as swtpm supports both.
Since you mention Windows 11, it is to be noted that it requires TPM v2.0. Taking that into account, this is the version of the protocol that will be used by default if you enable `vtpm` in your configuration.

The configuration should be very similar to what you suggest, there's a few new configuration options, the one that you will want to try out will be `vtpm = true`.

If possible, would you mind testing this to build a Windows 11 image when you have time? I've only basically tested this on a minimal configuration, and I've only taken a peek to ensure it was exposed through SeaBIOS (there's an extra configuration option there when a TPM is available), but I haven't yet tried it on a complete image build.

Thanks for opening the discussion on this front! Hope the latest patch will resolve your issue.

**Comment by lbajolet-hashicorp** [comment]
Hi @myllynen,

If this is good for the vTPM then on your side, I'll see that someone on the Packer team reviews the code, and we should be able to get that in the next release in its current state then, thanks for confirming!

For your other points, they would be a good case for more RFE yes! Please feel free to open as many issues as you see fit for this. Right now as you point out, it is always possible to add the arguments to the extra arguments to provide to qemu, but we can maybe add some more configuration options to make it easier to specify.

For the CD-ROM thing, I think you can provide them using the `cd_files` option? Works the same way as floppies, does that fix this problem for you?

**Comment by myllynen** [comment]
Thanks, I just filed #97 about UEFI so we can discuss that there.

Wrt CD-ROM you're correct, I got confused as I have few layers of automation on top and also vSphere in the mix and there mixing configuration files and drivers in the same CD-ROM would work differently but with Packer/Qemu that's no issue at all. So that part is all ok from Windows 11 perspective and I think only the UEFI is the only remaining open question.

FWIW, the automation I was referring to is this: https://github.com/myllynen/ansible-packer.

Thanks.
